// <auto-generated />
using System;
using ERP.Repository.PgSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Repository.PgSql.Migrations
{
    [DbContext(typeof(PgSqlDbContext))]
    [Migration("20240310094823_jobpostscofig")]
    partial class jobpostscofig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.GraduatesEntity.Graduate", b =>
                {
                    b.Property<int>("GraduateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GraduateID"));

                    b.Property<string>("GraduateCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraduateContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraduateDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraduateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GraduateID");

                    b.ToTable("Graduates");

                    b.HasData(
                        new
                        {
                            GraduateID = 1001,
                            GraduateCompany = "5993 Hills Burg, East Josianefort, Argentina",
                            GraduateContactNo = "450-228-5802",
                            GraduateDescription = "Internal",
                            GraduateName = "Reymundo"
                        },
                        new
                        {
                            GraduateID = 1002,
                            GraduateCompany = "971 Grady Springs, Veumfort, Grenada",
                            GraduateContactNo = "272-897-9194 x479",
                            GraduateDescription = "Dynamic",
                            GraduateName = "Baby"
                        },
                        new
                        {
                            GraduateID = 1003,
                            GraduateCompany = "442 Arno Way, Coltonstad, Guyana",
                            GraduateContactNo = "(966) 220-2767",
                            GraduateDescription = "Product",
                            GraduateName = "Zula"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.LabEntity.LabEquipment", b =>
                {
                    b.Property<int>("LabEquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabEquipmentID"));

                    b.Property<bool>("Avaialability")
                        .HasColumnType("boolean");

                    b.Property<string>("LabEquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LabSpaceId")
                        .HasColumnType("integer");

                    b.Property<string>("condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabEquipmentID");

                    b.ToTable("LabEquipments");

                    b.HasData(
                        new
                        {
                            LabEquipmentID = 3001,
                            Avaialability = false,
                            LabEquipmentName = "Jovan",
                            LabSpaceId = 0,
                            condition = "medium"
                        },
                        new
                        {
                            LabEquipmentID = 3002,
                            Avaialability = false,
                            LabEquipmentName = "Kiana",
                            LabSpaceId = 0,
                            condition = "medium"
                        },
                        new
                        {
                            LabEquipmentID = 3003,
                            Avaialability = false,
                            LabEquipmentName = "Vivien",
                            LabSpaceId = 0,
                            condition = "medium"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.LabEntity.LabSpace", b =>
                {
                    b.Property<int>("LabSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabSpaceId"));

                    b.Property<string>("LabSpaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabSpaceId");

                    b.ToTable("LabSpaces");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.RecruimentApplication", b =>
                {
                    b.Property<int>("RecruimentJobPostId")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CvFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("submissionDate")
                        .HasColumnType("date");

                    b.HasKey("RecruimentJobPostId");

                    b.HasIndex("PersonId");

                    b.ToTable("RecruimentApplication");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.RecruimentJobPost", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualificationsRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.ToTable("RecruimentJobs");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.TrainingEntity.InternShips.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LabEquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("InternPosition")
                        .HasColumnType("text");

                    b.Property<string>("JobDescriptionLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobPosts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "computer Engineering",
                            CompanyEmail = "Herman-Shields_Reichert80@hotmail.com",
                            CompanyName = "Herman - Shields",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "https://deborah.net"
                        },
                        new
                        {
                            Id = 102,
                            Category = "computer Engineering",
                            CompanyEmail = "CummingsWehnerandPfeffer.Parisian27@gmail.com",
                            CompanyName = "Cummings, Wehner and Pfeffer",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "http://anne.net"
                        },
                        new
                        {
                            Id = 103,
                            Category = "computer Engineering",
                            CompanyEmail = "GoldnerRogahnandWaters_Feil32@gmail.com",
                            CompanyName = "Goldner, Rogahn and Waters",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "https://elias.net"
                        },
                        new
                        {
                            Id = 104,
                            Category = "computer Engineering",
                            CompanyEmail = "Rogahn-Huels.Pollich18@hotmail.com",
                            CompanyName = "Rogahn - Huels",
                            InternPosition = "software engineer",
                            JobDescriptionLink = "http://baby.net"
                        },
                        new
                        {
                            Id = 105,
                            Category = "computer Engineering",
                            CompanyEmail = "McCulloughUllrichandFunk_Moen@hotmail.com",
                            CompanyName = "McCullough, Ullrich and Funk",
                            InternPosition = "data engineer",
                            JobDescriptionLink = "http://robin.info"
                        },
                        new
                        {
                            Id = 106,
                            Category = "computer Engineering",
                            CompanyEmail = "RitchieBeckerandWehner_Bins@gmail.com",
                            CompanyName = "Ritchie, Becker and Wehner",
                            InternPosition = "cyber security engineer",
                            JobDescriptionLink = "https://kamryn.biz"
                        },
                        new
                        {
                            Id = 107,
                            Category = "computer Engineering",
                            CompanyEmail = "DAmoreGroup.Bednar33@yahoo.com",
                            CompanyName = "D'Amore Group",
                            InternPosition = "data engineer",
                            JobDescriptionLink = "https://amber.name"
                        },
                        new
                        {
                            Id = 108,
                            Category = "computer Engineering",
                            CompanyEmail = "GutmannThielandWelch82@hotmail.com",
                            CompanyName = "Gutmann, Thiel and Welch",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "http://vivian.org"
                        },
                        new
                        {
                            Id = 109,
                            Category = "computer Engineering",
                            CompanyEmail = "WisokyGroup76@yahoo.com",
                            CompanyName = "Wisoky Group",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "http://libbie.net"
                        },
                        new
                        {
                            Id = 110,
                            Category = "computer Engineering",
                            CompanyEmail = "Langworth-Johnston.Weimann33@gmail.com",
                            CompanyName = "Langworth - Johnston",
                            InternPosition = "cyber security engineer",
                            JobDescriptionLink = "https://hermann.org"
                        },
                        new
                        {
                            Id = 111,
                            Category = "computer Engineering",
                            CompanyEmail = "AufderharandSons_Windler@yahoo.com",
                            CompanyName = "Aufderhar and Sons",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "http://jessie.info"
                        },
                        new
                        {
                            Id = 112,
                            Category = "computer Engineering",
                            CompanyEmail = "Shields-Trantow_Lesch@hotmail.com",
                            CompanyName = "Shields - Trantow",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "http://floyd.com"
                        },
                        new
                        {
                            Id = 113,
                            Category = "computer Engineering",
                            CompanyEmail = "KossLLC_Thompson@hotmail.com",
                            CompanyName = "Koss LLC",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "http://ismael.net"
                        },
                        new
                        {
                            Id = 114,
                            Category = "computer Engineering",
                            CompanyEmail = "Koss-Ondricka.Prosacco@hotmail.com",
                            CompanyName = "Koss - Ondricka",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "https://allen.name"
                        },
                        new
                        {
                            Id = 115,
                            Category = "computer Engineering",
                            CompanyEmail = "WhiteHagenesandSpinka74@hotmail.com",
                            CompanyName = "White, Hagenes and Spinka",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "https://vidal.name"
                        },
                        new
                        {
                            Id = 116,
                            Category = "computer Engineering",
                            CompanyEmail = "GreenholtHowellandHomenick77@hotmail.com",
                            CompanyName = "Greenholt, Howell and Homenick",
                            InternPosition = "cyber security engineer",
                            JobDescriptionLink = "https://ozella.net"
                        },
                        new
                        {
                            Id = 117,
                            Category = "computer Engineering",
                            CompanyEmail = "WolffWelchandKulas_Zboncak71@gmail.com",
                            CompanyName = "Wolff, Welch and Kulas",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "https://chandler.name"
                        },
                        new
                        {
                            Id = 118,
                            Category = "computer Engineering",
                            CompanyEmail = "SchmidtKingandWuckert.Parisian80@hotmail.com",
                            CompanyName = "Schmidt, King and Wuckert",
                            InternPosition = "software engineer",
                            JobDescriptionLink = "https://leonel.biz"
                        },
                        new
                        {
                            Id = 119,
                            Category = "computer Engineering",
                            CompanyEmail = "Tremblay-Kautzer86@hotmail.com",
                            CompanyName = "Tremblay - Kautzer",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "https://tremayne.com"
                        },
                        new
                        {
                            Id = 120,
                            Category = "computer Engineering",
                            CompanyEmail = "Keeling-Hackett_Terry18@hotmail.com",
                            CompanyName = "Keeling - Hackett",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "http://cruz.biz"
                        },
                        new
                        {
                            Id = 121,
                            Category = "computer Engineering",
                            CompanyEmail = "Wiegand-Barton.Kulas@gmail.com",
                            CompanyName = "Wiegand - Barton",
                            InternPosition = "software engineer",
                            JobDescriptionLink = "http://brennon.biz"
                        },
                        new
                        {
                            Id = 122,
                            Category = "computer Engineering",
                            CompanyEmail = "KrajcikandSons.Zboncak@gmail.com",
                            CompanyName = "Krajcik and Sons",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "https://andy.net"
                        },
                        new
                        {
                            Id = 123,
                            Category = "computer Engineering",
                            CompanyEmail = "Braun-Prosacco.Murazik12@gmail.com",
                            CompanyName = "Braun - Prosacco",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "http://gregorio.info"
                        },
                        new
                        {
                            Id = 124,
                            Category = "computer Engineering",
                            CompanyEmail = "KlockoBlockandOKon.Kassulke@yahoo.com",
                            CompanyName = "Klocko, Block and O'Kon",
                            InternPosition = "data engineer",
                            JobDescriptionLink = "http://jules.info"
                        },
                        new
                        {
                            Id = 125,
                            Category = "computer Engineering",
                            CompanyEmail = "Stracke-Adams_Herzog24@yahoo.com",
                            CompanyName = "Stracke - Adams",
                            InternPosition = "data engineer",
                            JobDescriptionLink = "http://lucas.name"
                        },
                        new
                        {
                            Id = 126,
                            Category = "computer Engineering",
                            CompanyEmail = "HaleyLefflerandCole.Wolff@gmail.com",
                            CompanyName = "Haley, Leffler and Cole",
                            InternPosition = "computer networks engineer",
                            JobDescriptionLink = "https://darius.net"
                        },
                        new
                        {
                            Id = 127,
                            Category = "computer Engineering",
                            CompanyEmail = "MullerJonesandGoldner.Veum42@gmail.com",
                            CompanyName = "Muller, Jones and Goldner",
                            InternPosition = "cyber security engineer",
                            JobDescriptionLink = "http://drew.biz"
                        },
                        new
                        {
                            Id = 128,
                            Category = "computer Engineering",
                            CompanyEmail = "BashirianRempelandBarrows.King@gmail.com",
                            CompanyName = "Bashirian, Rempel and Barrows",
                            InternPosition = "data engineer",
                            JobDescriptionLink = "http://hulda.org"
                        },
                        new
                        {
                            Id = 129,
                            Category = "computer Engineering",
                            CompanyEmail = "RiceHarberandSchuppe80@gmail.com",
                            CompanyName = "Rice, Harber and Schuppe",
                            InternPosition = "quality assurance Enginner",
                            JobDescriptionLink = "https://darrick.name"
                        },
                        new
                        {
                            Id = 130,
                            Category = "computer Engineering",
                            CompanyEmail = "BergeConnandPadberg_Jast74@gmail.com",
                            CompanyName = "Berge, Conn and Padberg",
                            InternPosition = "cyber security engineer",
                            JobDescriptionLink = "https://brandyn.info"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.TrainingEntity.StudentRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanySendersDesignation")
                        .HasColumnType("text");

                    b.Property<string>("CompanySendersName")
                        .HasColumnType("text");

                    b.Property<bool>("IsResponsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRequests");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.WorkLoadEntity.WorkingTask", b =>
                {
                    b.Property<int>("WorkingTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkingTaskId"));

                    b.Property<bool>("Assign")
                        .HasColumnType("boolean");

                    b.Property<string>("Decription")
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<double>("TimeAllocated")
                        .HasColumnType("double precision");

                    b.HasKey("WorkingTaskId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WorkingTasks");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BatchId");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurriculumId"));

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer");

                    b.HasKey("CurriculumId");

                    b.HasIndex("DegreeId");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DegreeId"));

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.HasKey("DegreeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Degree");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaluationId"));

                    b.Property<double>("FinalMarks")
                        .HasColumnType("double precision");

                    b.Property<double>("Marks")
                        .HasColumnType("double precision");

                    b.Property<int?>("ModuleOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EvaluationId");

                    b.HasIndex("ModuleOfferingId");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ModuleId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", b =>
                {
                    b.Property<int>("ModuleOfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleOfferingId"));

                    b.Property<int>("CoordinatorTeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalModeratorTeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeratorTeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleOfferingId");

                    b.HasIndex("CoordinatorTeacherId");

                    b.HasIndex("ExternalModeratorTeacherId");

                    b.HasIndex("ModeratorTeacherId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SemesterId");

                    b.ToTable("ModuleOffering");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingFirstExaminer", b =>
                {
                    b.Property<int>("ModuleOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleOfferingId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ModuleFirstExaminers");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingSecondExaminer", b =>
                {
                    b.Property<int>("ModuleOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleOfferingId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ModuleSecondExaminers");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingTeacher", b =>
                {
                    b.Property<int>("ModuleOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleOfferingId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ModuleTeachers");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleRegistration", b =>
                {
                    b.Property<int>("ModuleRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleRegistrationId"));

                    b.Property<int>("ModuleOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleRegistrationId");

                    b.HasIndex("ModuleOfferingId");

                    b.HasIndex("StudentId");

                    b.ToTable("ModuleRegistration");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecializationDegreeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("SemesterId");

                    b.HasIndex("BatchId");

                    b.HasIndex("SpecializationDegreeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GPA")
                        .HasColumnType("double precision");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.HasIndex("DegreeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1001,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            District = "",
                            DoB = new DateOnly(1, 1, 1),
                            Email = "Eryn97@gmail.com",
                            FirstName = "Eryn",
                            GPA = 0.0,
                            LastName = "Dicki",
                            NationalID = "",
                            Phone = "",
                            PhoneNumber = "",
                            RegistrationNum = "EG/2022/6407"
                        },
                        new
                        {
                            StudentId = 1002,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            District = "",
                            DoB = new DateOnly(1, 1, 1),
                            Email = "Dawson_Hudson70@hotmail.com",
                            FirstName = "Dawson",
                            GPA = 0.0,
                            LastName = "Hudson",
                            NationalID = "",
                            Phone = "",
                            PhoneNumber = "",
                            RegistrationNum = "EG/2023/2426"
                        },
                        new
                        {
                            StudentId = 1003,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            District = "",
                            DoB = new DateOnly(1, 1, 1),
                            Email = "Brielle.Labadie@hotmail.com",
                            FirstName = "Brielle",
                            GPA = 0.0,
                            LastName = "Labadie",
                            NationalID = "",
                            Phone = "",
                            PhoneNumber = "",
                            RegistrationNum = "EG/2020/3144"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.StudentResult", b =>
                {
                    b.Property<int>("StudentResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentResultId"));

                    b.Property<int?>("EvaluationId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<double>("StudentScore")
                        .HasColumnType("double precision");

                    b.HasKey("StudentResultId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentResult");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.Notification", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Person", "Person")
                        .WithMany("Notifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.RecruimentApplication", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Person", "Person")
                        .WithMany("RecruimentsApplications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.RecruimentJobPost", "RecruimentJobPost")
                        .WithMany("recruimentApplications")
                        .HasForeignKey("RecruimentJobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RecruimentJobPost");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.TrainingEntity.StudentRequest", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Student", "Student")
                        .WithMany("StudentRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.WorkLoadEntity.WorkingTask", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Teacher")
                        .WithMany("WorkingTasks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Curriculum", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Degree", null)
                        .WithMany("Curricula")
                        .HasForeignKey("DegreeId");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Degree", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Evaluation", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", null)
                        .WithMany("Evalutions")
                        .HasForeignKey("ModuleOfferingId");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Module", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Curriculum", null)
                        .WithMany("Modules")
                        .HasForeignKey("CurriculumId");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Coordinator")
                        .WithMany("CordinatingModules")
                        .HasForeignKey("CoordinatorTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "ExternalModerator")
                        .WithMany()
                        .HasForeignKey("ExternalModeratorTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Semester", "Semester")
                        .WithMany("Modules")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("ExternalModerator");

                    b.Navigation("Moderator");

                    b.Navigation("Module");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingFirstExaminer", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", "ModuleOffering")
                        .WithMany("FirstExaminers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Teacher")
                        .WithMany("FirstExaminersModules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleOffering");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingSecondExaminer", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", "ModuleOffering")
                        .WithMany("SecondExaminers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Teacher")
                        .WithMany("SecondExaminersModules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleOffering");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOfferingTeacher", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", "ModuleOffering")
                        .WithMany("Teachers")
                        .HasForeignKey("ModuleOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Teacher", "Teacher")
                        .WithMany("TeachingModules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleOffering");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleRegistration", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", "Module")
                        .WithMany("Registrations")
                        .HasForeignKey("ModuleOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Semester", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Degree", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationDegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Student", null)
                        .WithMany("Semesters")
                        .HasForeignKey("StudentId");

                    b.Navigation("Batch");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Student", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.StudentResult", b =>
                {
                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Evaluation", null)
                        .WithMany("Results")
                        .HasForeignKey("EvaluationId");

                    b.HasOne("ERP.Domain.Core.Entity.StudentEntity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.DepartmentEntity.RecruimentEntity.RecruimentJobPost", b =>
                {
                    b.Navigation("recruimentApplications");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Curriculum", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Degree", b =>
                {
                    b.Navigation("Curricula");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Evaluation", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.ModuleOffering", b =>
                {
                    b.Navigation("Evalutions");

                    b.Navigation("FirstExaminers");

                    b.Navigation("Registrations");

                    b.Navigation("SecondExaminers");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Person", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RecruimentsApplications");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Semester", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Student", b =>
                {
                    b.Navigation("Semesters");

                    b.Navigation("StudentRequests");
                });

            modelBuilder.Entity("ERP.Domain.Core.Entity.StudentEntity.Teacher", b =>
                {
                    b.Navigation("CordinatingModules");

                    b.Navigation("FirstExaminersModules");

                    b.Navigation("SecondExaminersModules");

                    b.Navigation("TeachingModules");

                    b.Navigation("WorkingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
